# источник: формы Bundler, «Gemfile» (path:, :path =>, блок path … do, git:) и Gemfile приложения Rails
source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 7.1.3"
gem "puma", ">= 5.0"
gem "billing", path: "engines/billing"
gem "admin_ui", :path => "engines/admin_ui", :require => false

path "components" do
  gem "auth"
  gem "search"
end

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails", git: "https://github.com/rspec/rspec-rails"
end
